name: Unit test the usagelogger

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install dependencies
        run: |
          luarocks install resurfaceio-logger-1.2-3.rockspec --local
      - name: Run test
        run: |
          luarocks test
