name: Unit test the usagelogger

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up OpenResty
        uses: leafo/gh-actions-openresty@v1
        with:
          openrestyVersion: "1.19.9.1"
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"
          withLuaPath: "/usr/local/openresty/luajit/"

      - name: Install dependencies
        run: |
          luarocks install --only-deps resurfaceio-logger-2.0-0.rockspec
      - name: Run test
        run: |
          resty tests/test.lua
